config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :headlines 
  root 'headlines#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :headlines
end

app/models/headline.rb
class Headline < ActiveRecord::Base

	belongs_to :user
	belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :headlines
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/headlines_controller.rb
class HeadlinesController < ApplicationController
    before_action :find_headline, only: [:show, :edit, :update, :destroy]

    
    def index
		@headlines = Headline.all.order("created_at DESC")
    end
    
    def show
    end
 
    def new
        @headline = current_user.headlines.build
        @categories = Category.all.map{ |c| [c.name, c.id] }
    end
    
    def create
        @headline = current_user.headlines.build(headline_params)
        @headline.category_id = params[:category_id]
        
        if @headline.save
			redirect_to root_path
		else
			render 'new'
	end
    end
    
    def edit
    end

	def update
		if @headline.update(headline_params)
			redirect_to headline_path(@headline)
		else
			render 'edit'
		end
	end

	def destroy
	    @headline.destroy
		redirect_to root_path
	end
	
    private
    
      def headline_params
          params.require(:headline).permit(:title, :description, :author, :category_id)
      end
      
        def find_headline
			@headline = Headline.find(params[:id])
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/headlines_helper.rb
module HeadlinesHelper
end

app/views/headlines/_form.html.erb
<%= simple_form_for @headline do |f| %>
    <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>
	<%= f.input :title, label: "Headline Title" %>
	<%= f.input :description %>
	<%= f.input :author %>
	<%= f.button :submit, :class => 'btn-custom2' %>
<% end %>

app/views/headlines/edit.html.erb
<h1>Edit Headline</h1>

<%= render 'form' %>

app/views/headlines/index.html.erb
<% @headlines.each do |headline| %>
  <h2><%= link_to headline.title, headline_path(headline) %></h2>
 <% end %>

app/views/headlines/new.html.erb
<h1>New Stories</h1>

<%= render 'form' %>

app/views/headlines/show.html.erb
<h2><%= @headline.title %></h2>
<h3><%= @headline.author %></h3>
<p><%= @headline.description %></p>

<%= link_to "Back", root_path, class: "btn btn-custom" %>

<% if user_signed_in? %>
<% if @headline.user_id == current_user.id %>
<%= link_to "Edit", edit_headline_path(@headline), class: "btn btn-custom" %>
<%= link_to "Delete", headline_path(@headline), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>
<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gubgook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
    <body>
        
    <nav class="navbar navbar-default">

		<div class="container">

			<div class="navbar-header">
				<%= link_to "News Review", root_path, class: "navbar-brand" %>
			</div>   
			
			<ul class="nav navbar-nav">
				<li><%= link_to "Sign Up", new_user_registration_path %></li>
				<% if user_signed_in? %>
					<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
				<% else %>	
					<li><%= link_to "Log In", new_user_session_path %></li>
				<% end %>
			</ul>
			
			<ul class="nav navbar-nav navbar-right">
			    <% if user_signed_in? %>
					<li><%= link_to "Add New Story", new_headline_path %></li>
					<% end %>
			</nav>
        
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
   
<%= yield %>
</body>
   

    
</html>